### ISSUE TITLE
下载地址位置内容为空

### ISSUE THREAD

**Issue by sinojelly** [xxNull-lsk/video_downloder#2]
查看浏览器开发人员工具，console窗口的输出，有如下一个错误：

videoDetail.afde97b6.js:7 Refused to create a worker from 'blob:https://appwXXXXX.h5.xiaoeknow.com/840f8ce4-1ac7-4e8c-a98a-b3d061e60672' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' 'self' *.xiaoeknow.com *.xiaoe-tech.com *.xeknow.com *.baidu.com *.qq.com *.jsdelivr.net assets.giocdn.com". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

不确定下载地址内容为空是否跟上面异常有关，看起来没有启用小鹅通油猴脚本，也有该报错。

目前发现两个问题：
1、下面这句话返回值是undefined
var detail_title = document.getElementsByClassName('detail-title')[0];

2、XMLHttpRequest.prototype.open 后面的代码没有运行。

**Comment by sinojelly** [comment]
通过看代码，xiaoeknow.js 油猴脚本 主要是把 视频名称、data_url（url中含有ts）、key_url（url中含有key）、referer_url 找到。
即使通过上述油猴脚本无法找到，通过 Fidder 也可以抓到。但是实际上，看起来 含有ts 的url可以抓到，但是含有 key 的url 抓不到。

是不是这个方法不能生效了呢？
![xiaoeknow-fail-fidder](https://user-images.githubusercontent.com/520711/100541378-96129380-327e-11eb-81ea-a32220672fe1.png)

**Comment by xxNull-lsk** [comment]
网站升级了，hook XMLHttpRequest.prototype.open失败导致的。手动获取这两个url吧

**Comment by sinojelly** [comment]
@xxNull-lsk 是不是不同的xiaoeknow店铺，播放视频的机制不一样？
我访问的店铺 通过fidder 跟踪来看，就不存在一个 key 文件（具体参见上面截图），是不是这种方式就不行？

**Comment by xxNull-lsk** [comment]
有可能,你试一下0.3版,看看能否获取到m3u8的url

**Comment by sinojelly** [comment]
@xxNull-lsk 0.3版非常好用，可以获取到 m3u8 的url。
虽然在 video downloader 中下载 m3u8 链接卡死，不能下载成功。
但我用那个url，在另外一个下载工具 M3U8Downloader 里面下载成功了：）

**Comment by sinojelly** [comment]
@xxNull-lsk 顺便问下，我在fiddler中看包含 m3u8 的 url 有很多个，看起来视频分了很多段。随便取一个url，把后面start/end相关部分去掉，下载也是不成功的。
但是你用的下面这句话获取的 url 是能成功下载的。你是怎么找到这个 m3u8 url的？
var url = window.myVideo.offsetParent.__vue__._data.props.url[0].url;

**Comment by xxNull-lsk** [comment]
卡死应该是因为你的那个视频没有加密,我写的这个工具只能下载加密的视频.一般只有收费的才加密,下载加密的前提已经购买了.
